name: Deploy to Heroku (Frontend)

on:
  push:
    branches:
      - master
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add frontend remote origin
        run: git remote add heroku-frontend https://heroku:${secrets.HEROKU_API_TOKEN}@git.heroku.com/${secrets.HEROKU_FRONTEND_APP_NAME}.git
      - name: Deploy frontend to Heroku
        run: git push heroku-frontend `git subtree split --prefix frontend master`:refs/heads/master --force


git remote add heroku-frontend https://heroku:b7ff03a5-8e72-4ecc-8060-4b17f5e0ba75@git.heroku.com/wedding-backend-rsvp..git